In [73]:
import pandas as pd
import numpy as np

In [74]:
credits_df=pd.read_csv(r"credits.csv")
movies_df=pd.read_csv(r"movies.csv")

In [75]:
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [76]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",10-12-2009,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",19-05-2007,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",26-10-2015,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",16-07-2012,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",07-03-2012,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [77]:
print(credits_df.shape)
print(movies_df.shape)

(4803, 4)
(4803, 20)

In [78]:
mov=movies_df.merge(credits_df,on="title")

In [79]:
mov

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]",...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,9367,"[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4804,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,72766,"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4805,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...",...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,231617,"[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4806,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,126186,"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4807,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...",...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,25975,"[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [80]:
mov.shape

(4808, 23)

In [81]:
mov.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4808 entries, 0 to 4807
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4808 non-null   int64
 1   genres                4808 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4808 non-null   int64
 4   keywords              4808 non-null   object
 5   original_language     4808 non-null   object
 6   original_title        4808 non-null   object
 7   overview              4805 non-null   object
 8   popularity            4808 non-null   float64
 9   production_companies  4808 non-null   object
 10  production_countries  4808 non-null   object
 11  release_date          4807 non-null   object
 12  revenue               4808 non-null   int64
 13  runtime               4806 non-null   float64
 14  spoken_languages      4808 non-null   object
 15  status                4808 non-null   object
 16  tagline               3964 non-null   object
 17  title                 4808 non-null   object
 18  vote_average          4808 non-null   float64
 19  vote_count            4808 non-null   int64
 20  movie_id              4808 non-null   int64
 21  cast                  4808 non-null   object
 22  crew                  4808 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.5+ KB

In [82]:
mov=mov[["movie_id","title","overview","genres","keywords","cast","crew"]]
mov.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [83]:
mov.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4808 entries, 0 to 4807
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4808 non-null   int64
 1   title     4808 non-null   object
 2   overview  4805 non-null   object
 3   genres    4808 non-null   object
 4   keywords  4808 non-null   object
 5   cast      4808 non-null   object
 6   crew      4808 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.5+ KB

In [84]:
mov.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [85]:
mov.dropna(inplace=True)

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\3258704376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov.dropna(inplace=True)

In [86]:
mov.duplicated().sum()

0

In [87]:
mov.iloc[1]

movie_id                                                  285
title                Pirates of the Caribbean: At World's End
overview    Captain Barbossa, long believed to be dead, ha...
genres      [{"id": 12, "name": "Adventure"}, {"id": 14, "...
keywords    [{"id": 270, "name": "ocean"}, {"id": 726, "na...
cast        [{"cast_id": 4, "character": "Captain Jack Spa...
crew        [{"credit_id": "52fe4232c3a36847f800b579", "de...
Name: 1, dtype: object

In [88]:
import ast

In [89]:
mov.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [90]:
def convert(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i["name"])
    return l

In [91]:
mov["genres"]=mov["genres"].apply(convert)
mov["keywords"]=mov["keywords"].apply(convert)
# mov["cast"]=mov["cast"].apply(convert)
mov.head()

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\21546284.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["genres"]=mov["genres"].apply(convert)
C:\Users\visha\AppData\Local\Temp\ipykernel_23492\21546284.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["keywords"]=mov["keywords"].apply(convert)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [92]:
mov["cast"]=mov["cast"].apply(convert)
mov.head()

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\3811902463.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["cast"]=mov["cast"].apply(convert)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [93]:
def convert2(obj):
    l=[]
    for i in ast.literal_eval(obj):
        if i["job"]=="Director" or i["job"]=="Original Music Composer":
            l.append(i["name"])
    return l

In [94]:
mov["crew"]=mov["crew"].apply(convert2)
mov.head()

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\1599014826.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["crew"]=mov["crew"].apply(convert2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[James Horner, James Cameron]"
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Gore Verbinski, Hans Zimmer]"
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[Thomas Newman, Sam Mendes]"
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Christopher Nolan]"
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [95]:
mov["overview"]=mov["overview"].apply(lambda x:x.split())

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\3696860921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["overview"]=mov["overview"].apply(lambda x:x.split())

In [96]:
mov.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[James Horner, James Cameron]"
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[Gore Verbinski, Hans Zimmer]"
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[Thomas Newman, Sam Mendes]"
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[Hans Zimmer, Christopher Nolan]"
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [97]:
mov["genres"]=mov["genres"].apply(lambda x:[i.replace(" ","") for i in x])
mov["cast"]=mov["cast"].apply(lambda x:[i.replace(" ","") for i in x])
mov["keywords"]=mov["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
mov["crew"]=mov["crew"].apply(lambda x:[i.replace(" ","") for i in x])

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\3474145397.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["genres"]=mov["genres"].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\visha\AppData\Local\Temp\ipykernel_23492\3474145397.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["cast"]=mov["cast"].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\visha\AppData\Local\Temp\ipykernel_23492\3474145397.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["keywords"]=mov["keywords"].apply(lambda x:[i.replace(" ","") for i in x])
C:\Users\visha\AppData\Local\Temp\ipykernel_23492\3474145397.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["crew"]=mov["crew"].apply(lambda x:[i.replace(" ","") for i in x])

In [98]:
mov.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesHorner, JamesCameron]"
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, HansZimmer]"
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes]"
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, ChristopherNolan]"
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [99]:
mov["tags"]=mov["overview"]+mov["genres"]+mov["keywords"]+mov["cast"]+mov["crew"]
mov.head()

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\4055337857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mov["tags"]=mov["overview"]+mov["genres"]+mov["keywords"]+mov["cast"]+mov["crew"]

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesHorner, JamesCameron]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, HansZimmer]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, ChristopherNolan]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [100]:
new_mov=mov[["movie_id","title","tags"]]
new_mov

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4803,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4804,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4805,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4806,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4807,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [101]:
new_mov["tags"]=new_mov["tags"].apply(lambda x:" ".join(x))
new_mov

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\2178859485.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov["tags"]=new_mov["tags"].apply(lambda x:" ".join(x))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4803,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4804,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4805,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4806,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4807,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [102]:
new_mov["tags"]=new_mov["tags"].apply(lambda x:x.lower())

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\1690896980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov["tags"]=new_mov["tags"].apply(lambda x:x.lower())

In [103]:
new_mov.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [106]:
import nltk
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [107]:
new_mov["tags"]=new_mov["tags"].apply(stem)
new_mov

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\1073790714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov["tags"]=new_mov["tags"].apply(stem)

,movie_id,title,tags
0,19995,Avatar,"22nd centuri , parapleg marin dispatch moon pa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa , long believ dead , come bac..."
2,206647,Spectre,cryptic messag bond â€™ past send trail uncov si...
3,49026,The Dark Knight Rises,"follow death district attorney harvey dent , b..."
4,49529,John Carter,"john carter war-weari , former militari captai..."
...,...,...,...
4803,9367,El Mariachi,el mariachi want play guitar carri famili trad...
4804,72766,Newlyweds,newlyw coupl 's honeymoon upend arriv respect ...
4805,231617,"Signed, Sealed, Delivered","`` sign , seal , deliv '' introduc dedic quart..."
4806,126186,Shanghai Calling,ambiti new york attorney sam sent shanghai ass...
4807,25975,My Date with Drew,ever sinc second grade first saw e.t . extrate...

In [108]:
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer(max_features=5000,stop_words="english")
cv

TfidfVectorizer(max_features=5000, stop_words='english')

In [109]:
print(cv.get_stop_words())

frozenset({'he', 'often', 'anywhere', 'when', 'we', 'no', 'something', 'ie', 'not', 'an', 'nine', 'nowhere', 'everywhere', 'rather', 'well', 'why', 'twenty', 'whether', 'ever', 'hundred', 'above', 'became', 'twelve', 'third', 'do', 'too', 'eg', 'me', 'she', 'two', 'would', 'besides', 'every', 'nor', 'never', 'then', 'and', 'down', 'latterly', 'hereby', 'their', 'six', 'these', 'so', 'alone', 'thereafter', 'four', 'one', 'bill', 'or', 'both', 'at', 'empty', 'eight', 'throughout', 'as', 'formerly', 'if', 'noone', 'eleven', 'becoming', 'within', 'sincere', 'back', 'move', 'in', 'its', 'becomes', 'all', 'can', 'yet', 'other', 'after', 'that', 'are', 'mine', 'anyway', 'been', 'ourselves', 'via', 'has', 'take', 'how', 'could', 'hereupon', 'but', 'amount', 'the', 'whither', 'them', 'also', 'cant', 'fire', 'now', 'seemed', 'none', 'nothing', 're', 'beyond', 'whereas', 'be', 'three', 'side', 'hers', 'over', 'detail', 'herein', 'seeming', 'although', 'thereupon', 'whoever', 'whereafter', 'while', 'into', 'herself', 'i', 'your', 'out', 'already', 'less', 'somehow', 'such', 'un', 'per', 'except', 'get', 'toward', 'sometime', 'therein', 'become', 'put', 'behind', 'may', 'same', 'anything', 'wherein', 'see', 'him', 'here', 'had', 'each', 'they', 'because', 'without', 'since', 'former', 'front', 'either', 'found', 'who', 'next', 'system', 'to', 'done', 'cannot', 'serious', 'by', 'give', 'ten', 'yourself', 'perhaps', 'which', 'fill', 'itself', 'own', 'thence', 'however', 'call', 'show', 'very', 'wherever', 'onto', 'on', 'others', 'part', 'made', 'my', 'latter', 'anyone', 'somewhere', 'another', 'whose', 'due', 'elsewhere', 'amongst', 'namely', 'many', 'were', 'sixty', 'once', 'again', 'seems', 'himself', 'what', 'whenever', 'am', 'a', 'five', 'below', 'between', 'any', 'fifteen', 'where', 'his', 'whom', 'moreover', 'much', 'might', 'for', 'towards', 'around', 'should', 'inc', 'therefore', 'someone', 'hence', 'mostly', 'cry', 'her', 'of', 'first', 'thick', 'off', 'our', 'nobody', 'con', 'forty', 'describe', 'everyone', 'being', 'was', 'yourselves', 'some', 'whereupon', 'seem', 'among', 'bottom', 'along', 'please', 'under', 'couldnt', 'together', 'further', 'nevertheless', 'whatever', 'have', 'afterwards', 'fifty', 'co', 'etc', 'there', 'beside', 'myself', 'top', 'from', 'thin', 'upon', 'than', 'otherwise', 'it', 'mill', 'still', 'meanwhile', 'amoungst', 'more', 'anyhow', 'name', 'against', 'thereby', 'else', 'few', 'themselves', 'with', 'ltd', 'go', 'beforehand', 'us', 'only', 'yours', 'whence', 'up', 'indeed', 'across', 'de', 'ours', 'though', 'thru', 'through', 'you', 'even', 'whereby', 'about', 'will', 'most', 'thus', 'hasnt', 'last', 'during', 'must', 'always', 'whole', 'find', 'everything', 'until', 'several', 'hereafter', 'sometimes', 'those', 'enough', 'is', 'neither', 'least', 'keep', 'this', 'before', 'full', 'almost', 'interest'})

In [110]:
cv.fit_transform(new_mov["tags"]).toarray().shape

(4805, 5000)

In [111]:
type(cv)

sklearn.feature_extraction.text.TfidfVectorizer

In [112]:
temp=TfidfVectorizer(max_features=5000,stop_words="english")

In [113]:
temp=temp.fit_transform(new_mov["tags"]).toarray()
temp

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [114]:
cv.get_feature_names()

C:\Users\visha\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1920',
 '1930',
 '1940',
 '1950',
 '1960',
 '1970',
 '1980',
 '1990',
 '19th',
 '19thcenturi',
 '20',
 '20th',
 '24',
 '25',
 '30',
 '3d',
 '40',
 '50',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'aaronzigman',
 'aasifmandvi',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'activ',
 'activist',
 'actor',
 'actress',
 'actual',
 'adam',
 'adambrodi',
 'adamgoldberg',
 'adamlefevr',
 'adamsandl',
 'adamscott',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adewaleakinnuoye',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrianmartinez',
 'adrienbrodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'advantag',
 'adventur',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'agbaj',
 'age',
 'agediffer',
 'agenc',
 'agenda',
 'agent',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airport',
 'al',
 'alanalda',
 'alanarkin',
 'alancum',
 'alanrickman',
 'alansilvestri',
 'alantudyk',
 'alaska',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcohol',
 'alecbaldwin',
 'alessandronivola',
 'alex',
 'alexandersiddig',
 'alexandredesplat',
 'alexapenavega',
 'alexborstein',
 'alexheff',
 'alexisbledel',
 'alfredhitchcock',
 'alfredmolina',
 'alfrewoodard',
 'ali',
 'alic',
 'alicedrummond',
 'aliciawitt',
 'alien',
 'alieninvas',
 'alienlife',
 'alik',
 'alilart',
 'aliv',
 'allancordun',
 'allen',
 'allencovert',
 'alleong',
 'alli',
 'allianc',
 'allisonjanney',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alzheim',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanfootbal',
 'ami',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amus',
 'amyadam',
 'amypoehl',
 'amyryan',
 'amysedari',
 'amysmart',
 'anagastey',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'anderson',
 'andi',
 'andiemacdowel',
 'andreamartin',
 'andrebraugh',
 'andrew',
 'andrewdali',
 'android',
 'andydick',
 'andygarcÃ­a',
 'andyricht',
 'andysamberg',
 'andyserki',
 'angel',
 'angelabassett',
 'angelinajoli',
 'angelo',
 'anger',
 'angri',
 'anim',
 'animalattack',
 'animalhorror',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'annalevin',
 'annapaquin',
 'annasophiarobb',
 'anndowd',
 'anne',
 'annebancroft',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annikaperga',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antonicoron',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'ape',
 'apocalyps',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'arena',
 'arielwint',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'arminmueller',
 'armor',
 'armsdeal',
 'armstrong',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'arthurj',
 'arthurtovey',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asid',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atomicbomb',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunjanueelli',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'avaacr',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'azizansari',
 'babe',
 'babi',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bag',
 'bahama',
 'bail',
 'bailey',
 'balanc',
 'ball',
 'ballet',
 'ban',
 'band',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bankrobberi',
 'baptist',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrypepp',
 'barryshabakahenley',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basilpoledouri',
 'basketbal',
 'batman',
 'battl',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beautifulwoman',
 'becam',
 'beccasweitz',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriend',
 'began',
 'begin',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'benchaplin',
 'bend',
 'benedictcumberbatch',
 'benedictwong',
 'benefit',
 'benfost',
 'bengazzara',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'benmendelsohn',
 'bennett',
 'benstil',
 'bent',
 'benwhishaw',
 'berlin',
 'bernardhil',
 'bernardle',
 'berniemac',
 'best',
 'bestfriend',
 'bet',
 'beth',
 'bethgrant',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billcamp',
 'billcobb',
 'billconti',
 'billduk',
 'billhad',
 'billi',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billnunn',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyburk',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'billydeewilliam',
 'billyslaught',
 'billywest',
 'billyzan',
 'biographi',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blackpeopl',
 'blade',
 'blakeclark',
 'blame',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'blythedann',
 'board',
 'boat',
 'bob',
 'bobbalaban',
 'bobbergen',
 'bobbi',
 'bobbycannaval',
 'bobbyfarrelli',
 'bobgunton',
 'bobhoskin',
 'bobodenkirk',
 'bobstephenson',
 'bodi',
 'bodyguard',
 'bokeemwoodbin',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'boot',
 'border',
 'bore',
 'born',
 'boss',
 'boston',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boydbank',
 'boydholbrook',
 'boyfriend',
 'braddourif',
 'bradgarrett',
 'bradleycoop',
 'bradleywhitford',
 'bradpitt',
 'bradwilliamhenk',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breckinmey',
 'brendanfras',
 'brendangleeson',
 'brendansextoniii',
 'brentbrisco',
 'brentspin',
 'brettcullen',
 'brettratn',
 'brian',
 'brianbless',
 'briancox',
 'briandennehi',
 'briandepalma',
 'briandoyle',
 'brianhow',
 'brianj',
 'briano',
 'briansteel',
 'briantyl',
 'brianvanholt',
 'bride',
 'bridesmaid',
 'bridg',
 'bridgettewilson',
 'brief',
 'brielarson',
 'brien',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucedern',
 'brucegreenwood',
 'brucemcgil',
 'brucesp',
 'brucewilli',
 'brutal',
 'bryan',
 'bryancranston',
 'bryansing',
 'brycedallashoward',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddycomedi',
 'budget',
 'build',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'businessman',
 'bust',
 'butler',
 'buy',
 'byrn',
 'ca',
 'cabin',
 'cain',
 'cal',
 'california',
 'callahan',
 'callumkeithrenni',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'cameronbright',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbel',
 'campbellscott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'cannib',
 'capabl',
 'capit',
 'captain',
 'captiv',
 'captur',
 'car',
 'caraccid',
 'caraseymour',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagallo',
 'carlagugino',
 'carlo',
 'carlosalazraqui',
 'carmen',
 'carmenelectra',
 'carol',
 'carolineaaron',
 'carolinegoodal',
 'carolkan',
 'carpent',
 'carrac',
 'carri',
 'carrie',
 'carriefish',
 'cartel',
 'carter',
 'carterburwel',
 'cary',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'catherineo',
 'catherinezeta',
 'cathey',
 'cathol',
 'catholic',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cedrictheentertain',
 'celebr',
 'celiaimri',
 'celiaweston',
 'cellphon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'certain',
 'chadmichaelmurray',
 'chain',
 'chainsaw',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chancekelli',
 'chang',
 'channingtatum',
 'chao',
 'chapter',
 'charact',
 'charg',
 'charismat',
 'charl',
 'charlesd',
 'charlesdurn',
 'charlesnapi',
 'charless',
 'charli',
 'charliesheen',
 'charlizetheron',
 'charlotterampl',
 'charltonheston',
 'charm',
 'chase',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheechmarin',
 'cheerlead',
 'chef',
 'chelcieross',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhood',
 'children',
 'chill',
 'chimcbrid',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'chloÃ«sevigni',
 'chocol',
 'choic',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chrisbrown',
 'chriscolumbu',
 'chriscoop',
 'chriselli',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrismessina',
 'chrismil',
 'chriso',
 'chrisowen',
 'chrisparnel',
 'chrispenn',
 'chrispin',
 'chrispratt',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christinaappleg',
 'christinaricci',
 'christinebaranski',
 'christma',
 'christmasparti',
 'christoph',
 'christophebeck',
 'christopherguest',
 'christopherlambert',
 'christopherle',
 'christopherlennertz',
 'christopherlloyd',
 'christophermcdonald',
 'christophermeloni',
 'christophermintz',
 'christopherplumm',
 'christopherwalken',
 'christopheryoung',
 'christophwaltz',
 'chronicl',
 'church',
 'cia',
 'ciarÃ¡nhind',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circumst',
 'citi',
 'citizen',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clancybrown',
 'clark',
 'clarkgregg',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'cleaduval',
 'clean',
 'clear',
 'clerk',
 'client',
 'cliffcurti',
 'cliffmartinez',
 'cliftoncollinsjr',
 'climat',
 'climb',
 'clinteastwood',
 'clinthoward',
 'clintmansel',
 'clinton',
 'cliveowen',
 'clock',
 'clone',
 'clorisleachman',
 'close',
 'closer',
 'clown',
 'club',
 'clue',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'codi',
 'codycameron',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colehaus',
 'colinfarrel',
 'colinfirth',
 'colinhank',
 'colinsalmon',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleencamp',
 'colleg',
 'collid',
 'collin',
 'collis',
 'colmfeor',
 'colmmeaney',
 'colonel',
 'coloni',
 'color',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comedi',
 'comedian',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'compani',
 'companion',
 'compet',
 'competit',
 'complet',
 'complex',
 'complic',
 'compos',
 'compton',
 'comput',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connel',
 'connienielsen',
 'connieray',
 'connor',
 'conquer',
 'conradvernon',
 'conscienc',
 'consequ',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'contest',
 'continu',
 'contract',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'core',
 'coreyburton',
 'coreystol',
 'corner',
 'corpor',
 'corps',
 'corrupt',
 'cost',
 'costum',
 'count',
 ...]

In [38]:
import nltk

In [40]:
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()

In [41]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [70]:
new_mov["tags"]=new_mov["tags"].apply(stem)
new_mov

C:\Users\visha\AppData\Local\Temp\ipykernel_23492\1073790714.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov["tags"]=new_mov["tags"].apply(stem)

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4803,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4804,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4805,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4806,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4807,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [104]:
import pandas as pd
import nltk
from nltk.corpus import stopwords

# Download the stop words data (you only need to do this once)
nltk.download('stopwords')
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    words = nltk.word_tokenize(text)
    return ' '.join([word for word in words if word.lower() not in stop_words])
new_mov['tags'] = new_mov['tags'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\visha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
C:\Users\visha\AppData\Local\Temp\ipykernel_23492\1019852225.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov['tags'] = new_mov['tags'].apply(remove_stopwords)

In [105]:
new_mov

,movie_id,title,tags
0,19995,Avatar,"22nd century , paraplegic marine dispatched mo..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa , long believed dead , come b..."
2,206647,Spectre,cryptic message bond â€™ past sends trail uncove...
3,49026,The Dark Knight Rises,following death district attorney harvey dent ...
4,49529,John Carter,"john carter war-weary , former military captai..."
...,...,...,...
4803,9367,El Mariachi,el mariachi wants play guitar carry family tra...
4804,72766,Newlyweds,newlywed couple 's honeymoon upended arrivals ...
4805,231617,"Signed, Sealed, Delivered","`` signed , sealed , delivered '' introduces d..."
4806,126186,Shanghai Calling,ambitious new york attorney sam sent shanghai ...
4807,25975,My Date with Drew,ever since second grade first saw e.t . extrat...

In [115]:
from sklearn.metrics.pairwise import cosine_similarity

In [116]:
cosine_similarity(temp)

array([[1.        , 0.01698304, 0.02575833, ..., 0.04257683, 0.00544857,
        0.        ],
       [0.01698304, 1.        , 0.04652653, ..., 0.0144125 , 0.        ,
        0.        ],
       [0.02575833, 0.04652653, 1.        , ..., 0.02157774, 0.        ,
        0.        ],
       ...,
       [0.04257683, 0.0144125 , 0.02157774, ..., 1.        , 0.02645766,
        0.0279942 ],
       [0.00544857, 0.        , 0.        , ..., 0.02645766, 1.        ,
        0.01673814],
       [0.        , 0.        , 0.        , ..., 0.0279942 , 0.01673814,
        1.        ]])

In [117]:
cosine_similarity(temp).shape

(4805, 4805)

In [118]:
sim=cosine_similarity(temp)
sim[0]

array([1.        , 0.01698304, 0.02575833, ..., 0.04257683, 0.00544857,
       0.        ])

In [123]:


def recommend(movie,n):
    movie_id=new_mov[new_mov["title"]==movie].index[0]
    distances=sim[movie_id]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:n+1]
    movies = [new_mov.iloc[score[0]]['title'] for score in movies_list]
    print(movies)

In [124]:
recommend("Batman v Superman: Dawn of Justice",5)

['Man of Steel', 'Batman Begins', 'Watchmen', 'Batman Returns', 'The Dark Knight']

In [49]:
recommend("Interstellar",10)

['Apollo 13', 'Space Pirate Captain Harlock', 'The Martian', 'Space Cowboys', 'The Right Stuff', '2001: A Space Odyssey', 'Moonraker', 'Silent Running', 'Galaxina', 'Capricorn One']

In [125]:
recommend("The Wolf of Wall Street",5)

['Wall Street', 'The Pursuit of Happyness', 'Harley Davidson and the Marlboro Man', 'Bernie', 'Bandits']

In [51]:
recommend("Spectre",7)

['Skyfall', 'Quantum of Solace', 'Never Say Never Again', 'Restless', 'Die Another Day', 'Safe Haven', 'From Russia with Love']

In [52]:
new_mov

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."
...,...,...,...
4803,9367,El Mariachi,el mariachi just want to play hi guitar and ca...
4804,72766,Newlyweds,a newlyw couple' honeymoon is upend by the arr...
4805,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduc a dedic q..."
4806,126186,Shanghai Calling,when ambiti new york attorney sam is sent to s...
4807,25975,My Date with Drew,ever sinc the second grade when he first saw h...

In [126]:
new_mov.to_csv("cleaned_movies.csv")

In [127]:
mov.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesHorner, JamesCameron]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, HansZimmer]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, ChristopherNolan]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [55]:
mov.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesHorner, JamesCameron]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, HansZimmer]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, ChristopherNolan]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [128]:
x=mov.copy()
x.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesHorner, JamesCameron]","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, HansZimmer]","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes]","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, ChristopherNolan]","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [129]:
x["tags"]=x["tags"].apply(lambda x:" ".join(x))
x["overview"]=x["overview"].apply(lambda x:" ".join(x))
x.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...","[JamesHorner, JamesCameron]","In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...","[GoreVerbinski, HansZimmer]","Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...","[ThomasNewman, SamMendes]",A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman, Anne...","[HansZimmer, ChristopherNolan]",Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"John Carter is a war-weary, former military ca..."

In [130]:
x.to_csv("dirty_movies.csv")